### ISSUE TITLE
Line break spacing

### ISSUE THREAD

**Issue by sarunaslite** [OptimoApps/statamic-bard-text-align#4] opened 2020-10-08 11:19 UTC
Statamic : 3.0.16
Statamic Bard Text Align : V1.0.1

Back:
<img width="875" alt="Screenshot 2020-10-08 at 14 17 41" src="https://user-images.githubusercontent.com/39726634/95451897-21536500-0971-11eb-8312-b360f16a4cb4.png">

Front:
<img width="933" alt="Screenshot 2020-10-08 at 14 17 48" src="https://user-images.githubusercontent.com/39726634/95451910-26181900-0971-11eb-8801-903fc7b52bea.png">

Problem:
`<span style="text-align:start;display :block"><br></span>`

**Comment by ssatz** [comment] 2020-10-08 14:21
Duplicate of  #3

**Closed by ssatz** 2020-10-08 14:21 UTC
