### ISSUE TITLE
Link break into a new line

### ISSUE THREAD

**Issue by sarunaslite** [OptimoApps/statamic-bard-text-align#3] opened 2020-10-08 09:48 UTC
Back:
<img width="294" alt="Screenshot 2020-10-08 at 12 47 57" src="https://user-images.githubusercontent.com/39726634/95442827-848aca80-0964-11eb-8646-11bf27f64d2a.png">

Front:
<img width="378" alt="Screenshot 2020-10-08 at 12 45 46" src="https://user-images.githubusercontent.com/39726634/95442649-52796880-0964-11eb-9be8-fe82ef3d7ee6.png">

**Comment by ssatz** [comment] 2020-10-08 09:54
Hi ,

I didn't get the issue here, the screenshot of front and back seems to be
same.

Could you please provide more details?

Best regards,
Satz

**Comment by sarunaslite** [comment] 2020-10-08 11:11
Statamic : 3.0.16
Statamic Bard Text Align : V1.0.1
Text with link:
<img width="872" alt="Screenshot 2020-10-08 at 14 10 05" src="https://user-images.githubusercontent.com/39726634/95451137-09c7ac80-0970-11eb-8333-7975ea22f56f.png">
After aligning text:
<img width="866" alt="Screenshot 2020-10-08 at 14 10 19" src="https://user-images.githubusercontent.com/39726634/95451158-10562400-0970-11eb-8911-5772e615b51b.png">

**Comment by ssatz** [comment] 2020-10-08 14:25
There is no way to extend Node from tiptap, no api was given from Statamic. I have posted in Discord, lets wait ! 

Below the extension class for mark
[Mark.js](https://github.com/statamic/cms/blob/master/resources/js/components/fieldtypes/bard/Mark.js)

Here is the doc
[Doc](https://statamic.dev/extending/bard#extensions)

**Comment by ssatz** [comment] 2020-10-08 16:00
@sarunaslite please check the issue in statamic https://github.com/statamic/cms/issues/944

**Comment by IllesAprod** [comment] 2021-05-25 06:15
Hi! I think https://github.com/statamic/cms/issues/944 is resolved, can u reopen this issue? We encountering the same problem as discussed above!

**Comment by swatty007** [comment] 2021-05-30 14:20
Same here a fix for this would be greatly appreciated.

**Comment by ssatz** [comment] 2021-05-30 14:24
@IllesAprod @swatty007  I've reopened the Issue. I am currently involved in other projects, so it will be delayed. I would also appreciate PR for this issue.

**Comment by swatty007** [comment] 2021-05-30 15:47
Just gave it a quick look, although I would love to, I think I would need to spend quite some time going through the not so short PoseMirror and tiptap documentation in the first place. Since I did not use any of those before 😅

However, from flying over the code and the behavior do I get it right, that the issue is that we are assigning the text alignment to every element in the selection via the “marking” extension. But what we actually want is to wrap the selection into a single parent node via the newly exposed “node” extension?
As the line break issue is not bound to the link. It does also happen, when you mark an object as italic, or bold within your aligned text.

**Comment by MrMooky** [comment] 2021-09-02 09:13
To my understanding the issue is simply caused by the `display: block` here:
https://github.com/OptimoApps/statamic-bard-text-align/blob/master/resources/js/TextAlign.js

Which produces the following output within Statamic:

<img width="470" alt="Screenshot 2021-09-02 at 11 10 11" src="https://user-images.githubusercontent.com/3603346/131816851-87434134-99c5-4ff3-9d67-325fd8a2ac25.png">

Removing the `display: block` should fix it, no?

**Comment by ssatz** [comment] 2022-03-19 12:31
Kindly send me a PR if this fix the issue

**Comment by alanpilloud** [comment] 2022-07-24 13:12
Hi @ssatz , could you please review @MrMooky 's work on this PR https://github.com/OptimoApps/statamic-bard-text-align/pull/10 ?

**Comment by ssatz** [comment] 2023-02-21 11:04
Statamic 3.4 Support #19

**Closed by ssatz** 2023-02-21 11:04 UTC
Labels: wontfix
